language: node_js
node_js:
  - 5.1
script:
  - npm run test
# after_success:
#   - npm run test:report
cache:
  directories:
    - node_modules
notifications:
  slack:
    on_success: change
    on_failure: change
  email: false
